/** Public facts only: name, year, city, live URL, and the pages already listed on the fiche. */
export const projectNotes: Record<string, string[]> = {
  "escapade-florale": [
    "Escapade Florale est une boutique en ligne de compositions florales, publiée en 2024 à Lille. Le site public est escapadeflorale.enconstru.fr. Depuis cette fiche, deux adresses sont ouvertes : la boutique, et une page produit, le bouquet cœur à cœur.",
    "Le travail livré est un site de vente, classé e-commerce. Un visiteur arrive sur le catalogue, ouvre un produit, et peut passer commande sur le site du fleuriste. Byte Force ne publie pas ici le nombre de commandes, le panier moyen, ni le trafic. Ces chiffres ne sont pas dans le dossier.",
    "La fiche sert à montrer ce qui est vérifiable : une boutique en ligne, un produit consultable, une ville et une année. Pour une entreprise qui veut le même type de catalogue, le point de départ est la liste des produits déjà vendus et la façon dont une commande arrive aujourd'hui, par téléphone, par message ou par un autre site.",
    "Le lien de service mène à la création de site. Le formulaire de contact, à Casablanca, sert à dire si le besoin est une boutique, un site vitrine, ou un logiciel derrière. La réponse part sous un jour ouvré.",
    "On ne décrit pas ici le paiement, la livraison des bouquets, ni le stock de fleurs. Ces choix sont sur le site du fleuriste, ou ils ne sont pas publics. La fiche s'arrête à ce qu'un visiteur peut ouvrir : la boutique, un produit, Lille, 2024. Une autre enseigne florale ne reprend pas cette page. Elle part de ses compositions et de la façon dont une commande est confirmée aujourd'hui.",
  ],
  "nu-lille": [
    "Nu Lille est un site pour une expérience gastronomique et événementielle à Lille, publié en 2023. L'adresse publique est nu-lille.fr. La page Événements est liée depuis cette fiche : c'est là que le programme se consulte.",
    "Le projet est classé e-commerce dans le catalogue Byte Force. La fiche ne détaille pas un tunnel de paiement, et elle n'invente pas un volume de réservations. Ce qui est public, c'est le site et la page des événements, au cœur de la métropole lilloise.",
    "Une maison qui vend des tables ou des événements a besoin que l'offre soit lisible avant le premier message : le lieu, le type de soirée, la façon de réserver. Le site porte cette lecture. Il ne remplace pas la salle, ni le service du soir.",
    "Il n'y a pas de témoignage client ni de chiffre de fréquentation dans le dossier. La preuve est l'adresse en ligne. Une entreprise qui reconnaît ce besoin peut écrire depuis la page contact, en décrivant l'offre telle qu'elle existe déjà.",
    "Nu Lille n'est pas présenté comme un logiciel de réservation. La fiche ne dit pas si une table se bloque en ligne ou seulement par message. Elle dit qu'un programme d'événements est public, à Lille, depuis 2023. Pour un lieu du même type, on part de ce programme et de la phrase que le visiteur doit lire avant d'écrire.",
  ],
  "meubles-de-septentrion": [
    "Meubles de Septentrion est une boutique de mobilier publiée en 2023 à Marcq-en-Barœul. Le site est meubles-de-septentrion.fr. Deux pages sont liées ici : la boutique, et une fiche produit, un corps à deux portes en métal et croisillons.",
    "Le catalogue Byte Force classe le projet en e-commerce. Le visiteur voit des pièces, ouvre une fiche, et commande sur le site du marchand. On ne publie pas le nombre de références, le délai de livraison, ni un taux de conversion : ces données ne sont pas dans la fiche.",
    "Un magasin de meubles a un problème simple à dire et long à bien faire : la pièce doit se comprendre à l'écran, avec ses dimensions et sa matière, avant un appel. Le site porte le catalogue. Il ne prétend pas gérer l'atelier ou le stock du dépôt.",
    "La création de site est le service lié. Pour un projet du même ordre, il faut la liste des pièces que l'on veut montrer en premier, et la façon dont une commande est confirmée aujourd'hui. On en parle depuis Casablanca, par le formulaire.",
    "La fiche produit liée montre une pièce précise, pas un catalogue inventé pour la page. On ne connaît pas, dans le dossier Byte Force, le nombre de meubles en ligne ni le délai annoncé au client. Marcq-en-Barœul et 2023 suffisent à situer le projet. Le reste se vérifie sur meubles-de-septentrion.fr.",
  ],
  "re-proche-de-moi": [
    "Proche de moi est une plateforme de mise en relation pour les commerces de proximité, publiée en 2024 à Lille. Le site est prochedemoi.fr. Trois pages publiques sont liées : la recherche, la carte, et la page Lille.",
    "Le problème de départ était concret : les commerces étaient difficiles à trouver dans un seul parcours. La solution publiée est la plateforme, avec la recherche, la carte et les fiches d'établissements. Le résultat que l'on peut vérifier est celui-ci : le site est en ligne à Lille depuis 2024. Pas un nombre d'inscrits, pas un chiffre d'affaires.",
    "Le projet est classé plateforme, et le service lié est le logiciel sur mesure, parce que le parcours n'est pas une simple page vitrine. Un habitant cherche, voit une carte, ouvre une fiche. C'est le produit. On ne le présente pas comme un CRM, ni comme un outil de caisse pour les boutiques.",
    "Une entreprise qui a le même genre de parcours — chercher, localiser, ouvrir une fiche — peut décrire le sien par le formulaire. On regarde d'abord si un outil du marché le fait déjà. On n'écrit pas un logiciel pour remplacer une carte qui suffit.",
    "Les trois adresses liées, recherche, carte et Lille, sont le parcours que l'on peut refaire sans compte. On ne publie pas le nombre de commerces inscrits. Si ce nombre compte pour décider, il se lit sur le site, pas dans une phrase ajoutée ici. Le projet reste daté de 2024, à Lille.",
  ],
  "ambulances-valcq": [
    "Ambulances Valcq est un site vitrine pour le transport sanitaire à Roubaix, publié en 2022. L'adresse publique est ambulances-valcq.fr. Aucune page intérieure n'est listée sur cette fiche : le site lui-même est la référence.",
    "Le travail est une vitrine. Elle présente l'activité professionnelle. Elle ne publie pas, ici, d'agrément, de flotte, de zone d'intervention chiffrée, ni d'avis de patients. Ces éléments, s'ils existent, sont sur le site du transporteur, pas inventés dans le catalogue Byte Force.",
    "Pour une activité locale, la vitrine a un rôle limité et utile : dire qui appelle, pour quel transport, et comment joindre le standard. Le reste du métier, les courses et les plannings, n'est pas décrit comme un logiciel dans ce projet.",
    "Le service lié est la création de site. Une société de service qui veut la même chose commence par ce que le visiteur doit comprendre en une minute, et par le numéro ou le formulaire qui reçoit la demande. On répond depuis Casablanca, sous un jour ouvré.",
    "2022 est l'année publiée, Roubaix est la ville. Il n'y a pas d'autre page intérieure dans cette fiche, donc on n'invente pas un espace patient ou un planning de courses. Le site ambulances-valcq.fr porte ce que l'entreprise a choisi de montrer. La fiche Byte Force ne va pas plus loin. Le transport sanitaire reste décrit comme une activité, pas comme un logiciel de régulation.",
  ],
  "les-hauts-paysages": [
    "Les Hauts Paysages est un site vitrine d'aménagements paysagers dans le Nord, publié en 2023. L'adresse est leshautspaysages.fr. La page Prestations est liée : c'est là que les travaux proposés sont décrits.",
    "Le catalogue classe le projet en vitrine, pas en boutique. On ne montre pas un panier. On montre une activité : concevoir et aménager des espaces verts. Aucun nombre de chantiers, aucun montant de devis, aucune photo d'équipe n'est ajouté ici.",
    "Le site sert à ce qu'un propriétaire comprenne l'offre avant d'écrire. La page des prestations porte cette lecture. Le suivi de chantier, les plans et les factures ne font pas partie de ce qui est publié comme logiciel.",
    "La création de site est le service associé. Pour un métier du même type, il faut la liste des prestations que l'on veut nommer, et la façon dont une demande arrive aujourd'hui. Le contact à Casablanca sert à cadrer cela, sans promettre un classement sur Google.",
    "Le Nord est indiqué comme zone, pas comme une ville unique, et l'année est 2023. La page Prestations est le seul intérieur lié. On ne décrit pas un jardin livré, une surface, ou un client. Ces détails, s'ils sont publics, sont sur leshautspaysages.fr. La fiche ne promet pas non plus que le site reçoit les demandes : elle montre que les prestations sont écrites, et que le reste du chantier n'est pas un logiciel publié.",
  ],
  dealkhir: [
    "Dealkhir est une plateforme pour le don et les organisations, publiée en 2024 à Casablanca. Le site public est dealkhir.ma. La page Organisations est liée depuis cette fiche.",
    "Le problème était l'absence d'un espace commun pour le don et les organisations. La solution publiée est la plateforme. Le résultat vérifiable est le site en ligne à Casablanca depuis 2024. Dealkhir n'est pas un pipeline commercial, et on ne l'utilise pas comme preuve d'un CRM.",
    "Le projet est classé plateforme. Le service lié est le logiciel sur mesure. Un visiteur peut voir les organisations. On ne publie pas le montant des dons, le nombre d'inscrits, ni un témoignage. Ces chiffres ne sont pas dans le dossier public.",
    "C'est le projet casablancais que l'on peut ouvrir. Le bureau de Byte Force est aussi à Casablanca, au Technopark. Cela ne fait pas de Dealkhir un logiciel de gestion interne : c'est un produit publié, avec son adresse et sa page organisations.",
    "La page Organisations est le seul intérieur lié. On n'y ajoute pas, depuis ici, une liste d'associations ni un total de dons. 2024 est l'année du catalogue. Quelqu'un qui veut le même type d'espace décrit qui publie une organisation et ce qu'un don doit permettre, puis on regarde le site actuel avant d'écrire autre chose.",
  ],
  "coco-inbox": [
    "Coco Inbox est un produit publié en 2024 à Montréal. Il couvre l'email temporaire, les fichiers chiffrés et les notes sécurisées. L'adresse est cocoinbox.com. Aucune page intérieure n'est listée : le produit se consulte à la racine.",
    "Le problème de départ : l'email, les fichiers et les notes partaient sans limite claire de durée ou de destinataire. La solution est le produit publié. Le résultat que l'on affirme est seulement celui-ci : il est en ligne, depuis Montréal, depuis 2024.",
    "Ce n'est pas un CRM, pas une boîte mail d'entreprise, et pas un outil de prospection. Le catalogue le classe en plateforme. Le service lié est le logiciel sur mesure, parce que le produit a son propre parcours, pas une page vitrine.",
    "On ne publie pas un nombre d'utilisateurs ni un niveau de chiffrement détaillé au-delà de ce que le produit dit lui-même. La fiche renvoie au site. Une entreprise qui veut un outil du même ordre décrit la donnée qui part aujourd'hui, et à qui, avant qu'on décide s'il faut l'écrire.",
    "Montréal, 2024, cocoinbox.com : ce sont les trois faits stables. Le produit se consulte sans page intérieure listée dans le catalogue. On ne le range pas avec les boutiques, ni avec les vitrines. C'est un outil publié, et la capture sur la fiche montre l'écran, pas un résultat commercial.",
  ],
  uas: [
    "UAS, Universal Aviation Services, est un site e-commerce pour le secteur aéronautique, publié en 2023 à Casablanca. L'adresse publique est uas.ma. Aucune page intérieure n'est listée sur cette fiche.",
    "Le catalogue le classe en e-commerce, et le service lié est la création de site. On ne le confond pas avec un autre projet : ce n'est pas une plateforme automobile, et ce n'est pas un logiciel de maintenance d'avions décrit ici. C'est le site de vente publié pour cette activité.",
    "Aucun chiffre de pièces, de commandes ou de clients n'est dans le dossier. La preuve est l'adresse. Une entreprise du même secteur qui veut un catalogue en ligne commence par les produits qu'elle vend déjà, et par la façon dont une commande est confirmée.",
    "Le bureau qui a porté le projet est à Casablanca. Cela ne crée pas une deuxième société, ni un bureau sur l'aéroport. Pour en parler, le formulaire de contact suffit : nom, email, et ce que le site doit permettre de commander.",
    "uas.ma est l'adresse à ouvrir. 2023 est l'année du catalogue. Il n'y a pas de page intérieure liée, donc on ne décrit pas une fiche produit précise. Le secteur indiqué est l'aéronautique, au Maroc, et le format est une boutique en ligne. Rien d'autre n'est affirmé. On ne parle pas de pièces détachées, de stocks, ni d'un compte client. La page s'arrête à ce site.",
  ],
  tourispeak: [
    "Tourispeak est un réseau pour l'industrie du tourisme, publié en 2024 à Montréal. Le site est tourispeak.com. La page À propos est liée. Le parcours public comprend aussi des visites audio : c'est ce que le site montre, pas un chiffre de téléchargements.",
    "Le problème était l'absence d'un site public pour le réseau et les visites. La solution est le site publié. Le résultat vérifiable : il est en ligne, depuis Montréal, depuis 2024. On ne le présente pas comme un logiciel vertical pour un office de tourisme réglementé.",
    "Le projet est une plateforme. Le service lié est le logiciel sur mesure. Le réseau a son propre parcours, distinct d'un modèle d'agence recopié. On ne publie pas le nombre de membres, ni un taux d'écoute des visites.",
    "Une organisation qui veut un espace du même type décrit qui publie, qui visite, et ce qu'une fiche doit contenir. On regarde ensuite si le site actuel peut être continué, ou s'il faut un parcours nouveau. La demande part par le contact, à Casablanca.",
    "La page À propos liée situe le réseau. Les visites audio se voient sur tourispeak.com, pas dans un chiffre d'écoute ajouté ici. Montréal et 2024 placent le projet. On ne le mélange pas avec une boutique, ni avec un site vitrine d'agence de voyages.",
  ],
  "agency-wonderland": [
    "Agency Wonderland est un site de studio visuel à Marrakech, publié en 2024. L'adresse est agencywonderland.com. La galerie est liée : c'est la page où le travail du studio se regarde.",
    "Le catalogue classe le projet en vitrine, et le service lié est le design graphique. Le site présente une production visuelle. Il ne publie pas, dans cette fiche, de palmarès, de nombre de campagnes, ni de nom de clients au-delà du studio lui-même.",
    "Une galerie a un rôle précis : montrer le travail avant une conversation. Le reste, les devis et le suivi de production, n'est pas décrit comme un logiciel ici. On ne transforme pas cette vitrine en preuve d'une identité de marque complète livrée clé en main.",
    "Pour un studio qui veut la même chose, il faut les pièces à montrer et l'ordre dans lequel on les voit. On cadre cela depuis Casablanca. Le formulaire demande le projet, pas un brief de cinquante pages.",
    "La galerie est le seul intérieur lié. Marrakech et 2024 placent le studio. L'adresse agencywonderland.com est en http dans le dossier : on la laisse telle quelle, sans prétendre qu'un certificat a été ajouté par cette fiche. Le travail montré est visuel. Le suivi de production n'y est pas décrit. On n'ajoute pas de logo client ni de campagne nommée. Le studio publié s'appelle Agency Wonderland.",
  ],
  "snapchat-collect": [
    "Snapchat Collect est un outil de collecte et de redirection pour des campagnes sociales, publié en 2024. Il opère entre Marseille et Tanger. L'adresse publique est snapchat-collect.vercel.app, en français. Aucune page intérieure n'est listée.",
    "Le catalogue le classe en plateforme. Le service lié est le développement d'API, parce que le travail est la collecte et la redirection, pas une vitrine. On ne publie pas le nombre de clics, le coût d'une campagne, ni un taux de conversion. Ces mesures ne sont pas dans la fiche.",
    "Le produit reçoit un passage et l'oriente. C'est tout ce que l'on affirme. On ne le présente pas comme un gestionnaire de publicités, ni comme un CRM des personnes qui ont cliqué.",
    "Une équipe qui a le même besoin décrit la source du clic et la page d'arrivée, puis ce qui doit être enregistré. Si un outil du marché le fait déjà, on le dit. Sinon, on cadre l'API. Le contact est à Casablanca, et la réponse part sous un jour ouvré.",
    "Tanger est la ville du catalogue, et le dossier dit aussi Marseille, parce que l'outil opère entre les deux. 2024 est l'année. L'adresse publique est en français. On n'ajoute pas de campagne exemple, ni de marque annonceur. La fiche s'arrête à la collecte et à la redirection. Le lien de service reste l'API, pas la création d'un site vitrine.",
  ],
};
