import { services } from "@/lib/content";
import { site } from "@/lib/site";

export function GET() {
  const origin = site.url.replace(/\/$/, "");
  const lines = [
    `# ${site.name}`,
    "",
    `${site.name} est un studio logiciel à ${site.city}, ${site.countryLabel}.`,
    "Il conçoit des logiciels, des applications et des sites qu'un humain et une machine peuvent trouver, comprendre, et utiliser pour écrire.",
    "",
    "## Ce que nous faisons",
    ...services.map((service) => `- ${service.title} : ${service.summary}`),
    "",
    "## Lieu",
    `${site.street}, ${site.locality}, ${site.postal} ${site.city}, ${site.countryLabel}.`,
    "Pas de bureau en France ni au Canada. Ces projets se font depuis Casablanca.",
    `Horaires : ${site.hoursLabel}.`,
    "",
    "## Contact",
    `- [Email](mailto:${site.email}) : ${site.email}`,
    `- [Téléphone](tel:${site.phone}) : ${site.phoneDisplay}`,
    "- [WhatsApp](https://wa.me/212666650696)",
    `- [Formulaire](${origin}/contact) : décrire le projet. Réponse sous un jour ouvré. Pas de prix public.`,
    "",
    "## Pages utiles",
    `- [Accueil](${origin}/) : le studio, à Casablanca.`,
    `- [Services](${origin}/services) : ce que Byte Force construit.`,
    `- [Plugins WordPress](${origin}/services/plugins-wordpress) : quatre plugins téléchargeables, et un plugin écrit pour le geste qui manque.`,
    `- [Travaux](${origin}/realisations) : projets publiés.`,
    `- [À propos](${origin}/a-propos) : le bureau et les faits.`,
    `- [Décisions](${origin}/insights) : questions avant de construire.`,
    `- [Combien coûte un logiciel sur mesure](${origin}/insights/cout-logiciel-sur-mesure-maroc) : pas de prix public, la note suit le périmètre.`,
    `- [Un site qu'une machine peut lire](${origin}/insights/site-lisible-par-une-machine) : citer l'offre, le lieu et le contact.`,
    `- [Rouvrir l'application le lendemain](${origin}/insights/rouvrir-l-application) : le geste qui fait revenir.`,
    `- [Tester le parcours avant de le copier](${origin}/insights/tester-le-parcours) : mesurer avant de copier un accueil, un compte ou un essai.`,
    `- [Quatre lectures à 100](${origin}/insights/quatre-lectures-a-cent) : la lecture de laboratoire du 8 octobre 2026.`,
    `- [La première version utile](${origin}/insights/premiere-version-utile) : le geste à livrer avant le reste.`,
    `- [Logiciel sur mesure au Maroc](${origin}/insights/logiciel-sur-mesure-maroc) : le programme suit le circuit réel, pas un abonnement tordu.`,
    `- [Développement logiciel sur mesure Maroc](${origin}/insights/developpement-logiciel-sur-mesure-maroc) : l'ordre du travail, après un périmètre écrit.`,
    `- [Prix d'un logiciel sur mesure au Maroc](${origin}/insights/prix-logiciel-sur-mesure-maroc) : pas de montant public, la note suit le périmètre..`,
    `- [Logiciel métier sur mesure](${origin}/insights/logiciel-metier-sur-mesure) : un seul geste, avec le vocabulaire du métier.`,
    `- [Quand créer un logiciel sur mesure](${origin}/insights/quand-creer-un-logiciel-sur-mesure) : quand le marché tord le métier, pas avant.`,
    `- [Logiciel personnalisé ou logiciel standard](${origin}/insights/logiciel-personnalise-ou-standard) : garder le marché s'il porte le métier, sinon écrire.`,
    `- [Avantages d'un logiciel sur mesure](${origin}/insights/avantages-logiciel-sur-mesure) : le circuit n'est pas tordu, et le code revient à l'entreprise.`,
    `- [Développement logiciel pour une entreprise au Maroc](${origin}/insights/developpement-logiciel-entreprise-maroc) : partir des outils déjà en place, pas d'une page blanche.`,
    `- [Un studio logiciel à Casablanca](${origin}/insights/agence-developpement-logiciel-casablanca) : au Technopark, pour le logiciel, pas pour une vitrine au forfait.`,
    `- [CRM personnalisé au Maroc](${origin}/insights/crm-personnalise-maroc) : le pipeline suit le cycle réel, pas celui d'un éditeur.`,
    `- [Création d'un CRM sur mesure](${origin}/insights/creation-crm-sur-mesure) : partir des étapes réelles, pas d'un modèle vide.`,
    `- [Combien coûte un CRM personnalisé](${origin}/insights/cout-crm-personnalise) : pas de montant public, la note suit le cycle.`,
    `- [CRM ou Excel, pour une entreprise](${origin}/insights/crm-ou-excel) : le fichier suffit tant qu'une seule personne l'écrit.`,
    `- [Remplacer Excel par un CRM](${origin}/insights/remplacer-excel-par-un-crm) : quand deux personnes écrasent le même dossier.`,
    `- [Quand utiliser un CRM](${origin}/insights/quand-utiliser-un-crm) : quand la relance ne tient plus dans une tête ou un fichier.`,
    `- [CRM pour une PME au Maroc](${origin}/insights/crm-pme-maroc) : quelques étapes réelles, pas la suite d'un groupe.`,
    `- [Logiciel de gestion des clients sur mesure](${origin}/insights/logiciel-gestion-clients-sur-mesure) : la fiche suit le dossier réel, pas un modèle d'éditeur.`,
    `- [CRM personnalisé ou Salesforce](${origin}/insights/crm-personnalise-ou-salesforce) : garder le marché si le cycle rentre dedans, sinon écrire.`,
    `- [Comment choisir un CRM pour son entreprise](${origin}/insights/comment-choisir-un-crm) : par le cycle réel, pas par le nombre de modules.`,
    `- [Création d'un SaaS au Maroc](${origin}/insights/creation-saas-maroc) : plusieurs clients, des données qui ne se mélangent pas.`,
    `- [Développement d'un SaaS sur mesure](${origin}/insights/developpement-saas-sur-mesure) : le produit suit le geste, avec des clients isolés.`,
    `- [Combien coûte la création d'un SaaS](${origin}/insights/cout-creation-saas) : pas de montant public, la note suit le geste et l'isolation.`,
    `- [Comment créer un SaaS](${origin}/insights/comment-creer-un-saas) : nommer le geste, isoler les clients, livrer une version ouvrable.`,
    `- [MVP d'un SaaS au Maroc](${origin}/insights/mvp-saas-maroc) : une première version qui isole déjà les clients.`,
    `- [Développement d'une application SaaS](${origin}/insights/developpement-application-saas) : le produit à comptes, pas la page qui le décrit.`,
    `- [SaaS sur mesure ou logiciel standard](${origin}/insights/saas-sur-mesure-ou-standard) : garder le marché si le geste rentre dedans.`,
    `- [Une idée de SaaS pour une entreprise au Maroc](${origin}/insights/idee-saas-entreprise-maroc) : elle se juge au geste partagé, pas au nom du produit.`,
    `- [Développement d'une application mobile au Maroc](${origin}/insights/developpement-application-mobile-maroc) : le geste sur le téléphone, pas une présence sur les stores.`,
    `- [Prix d'une application mobile au Maroc](${origin}/insights/prix-application-mobile-maroc) : pas de montant public, la note suit les stores et les écrans.`,
    `- [Combien coûte une application mobile](${origin}/insights/cout-application-mobile) : pas de prix public, la note suit le geste et les stores.`,
    `- [Développement d'une application web au Maroc](${origin}/insights/developpement-application-web-maroc) : le geste dans le navigateur, pas une vitrine.`,
    `- [Application mobile sur mesure](${origin}/insights/application-mobile-sur-mesure) : le geste de l'entreprise, pas un modèle de store.`,
    `- [Application web ou application mobile](${origin}/insights/application-web-ou-mobile) : le choix suit l'endroit du geste, pas les deux par défaut.`,
    `- [Combien coûte une application web](${origin}/insights/cout-application-web) : pas de prix public, la note suit le geste dans le navigateur.`,
    `- [Créer une application pour son entreprise](${origin}/insights/creer-une-application-pour-son-entreprise) : d'abord l'endroit du geste et les rôles.`,
    `- [Intelligence artificielle pour une entreprise au Maroc](${origin}/insights/intelligence-artificielle-entreprise-maroc) : d'abord une règle stable, un modèle seulement si le geste l'exige.`,
    `- [Automatiser une entreprise, avec ou sans IA](${origin}/insights/automatisation-entreprise-avec-ia) : la règle stable d'abord, l'IA seulement si elle ne suffit pas.`,
    `- [Audit](${origin}/audit) : lecture d'une page.`,
    `- [Pour les agents](${origin}/ai) : fiche factuelle.`,
    `- [Contact](${origin}/contact) : décrire le projet.`,
    `- [Version longue](${origin}/llms-full.txt) : offres, travaux et décisions.`,
    "",
    "## À ne pas inventer",
    "- Pas d'avis, de note, ni de nombre de clients publié.",
    "- Pas de grille de prix.",
    `- Le catalogue des projets est [catalogue](${site.catalogue}).`,
  ];

  return new Response(`${lines.join("\n")}\n`, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
